export const homeBedroomGroups = [
  {
    bedrooms: 1,
    label: '1 Bedroom',
    properties: [
      { name: 'Christmas Cottage', path: '/rental-properties/christmas-cottage' },
      { name: 'Harbor Lights', path: '/rental-properties/harbor-lights' },
      { name: 'In Harmony Retreat', path: '/rental-properties/in-harmony-retreat' },
      { name: 'Island Gardens', path: '/rental-properties/island-gardens' },
      { name: 'Island Vibes', path: '/rental-properties/island-vibes' },
      { name: 'Lavender Hill Unit 10-E', path: '/rental-properties/lavender-hill-unit-10-e-' },
      { name: 'Lots of Knots', path: '/rental-properties/lots-of-knots-' },
      { name: 'MandeVilla at Ixora', path: '/rental-properties/mandevilla-at-ixora' },
      { name: 'Paradise Carest', path: '/rental-properties/paradise-carest' },
      { name: 'Sun, Moon and Stars', path: '/rental-properties/sun%2C-moon-and-stars' },
      { name: 'The Little Easy', path: '/rental-properties/the-little-easy' },
      { name: 'Windwardside Guest Cottage', path: '/rental-properties/windwardside-guest-cottage' },
      { name: 'Windwardside Main House', path: '/rental-properties/windwardside-main-house' },
    ],
  },
  {
    bedrooms: 2,
    label: '2 Bedrooms',
    properties: [
      { name: 'Brezza di Mare', path: '/rental-properties/brezza-di-mare' },
      { name: 'Desert Rose Villa', path: '/rental-properties/desert-rose-villa' },
      { name: 'Fish Tales', path: '/rental-properties/fish-tales' },
      { name: 'Miles Away', path: '/rental-properties/miles-away' },
      { name: 'Mystical Mermaid Villa', path: '/rental-properties/mystical-mermaid-villa' },
      { name: 'Notre Ciel', path: '/rental-properties/notre-ciel' },
      { name: 'Orchid Garden', path: '/rental-properties/orchid-garden' },
      { name: 'Samba Azul', path: '/rental-properties/samba-azul' },
      { name: 'San Costanzo', path: '/rental-properties/san-costanzo' },
      { name: 'Sapphire Peak', path: '/rental-properties/sapphire-peak' },
      { name: 'Sea Palace Retreat', path: '/rental-properties/sea-palace-retreat' },
      { name: 'Sol Cottage Villa', path: '/rental-properties/sol-cottage-villa' },
      { name: 'Sol La Vie', path: '/rental-properties/sol-la-vie' },
      { name: 'Sunset Paradise', path: '/rental-properties/sunset-paradise' },
      { name: 'Villa Madeline', path: '/rental-properties/villa-madeline' },
      { name: 'Waterklip', path: '/rental-properties/waterklip' },
    ],
  },
  {
    bedrooms: 3,
    label: '3 Bedrooms',
    properties: [
      { name: 'Alta Vista', path: '/rental-properties/alta-vista' },
      { name: 'Arco Iris', path: '/rental-properties/arco-iris' },
      { name: 'Astral Villa', path: '/rental-properties/astral-villa' },
      { name: 'Beyond the Sea', path: '/rental-properties/beyond-the-sea' },
      { name: 'Cara Mia', path: '/rental-properties/cara-mia' },
      { name: 'East End Seascape', path: '/rental-properties/east-end-seascape' },
      { name: 'Hart Bay Beach House', path: '/rental-properties/hart-bay-beach-house' },
      { name: 'Idyllic Villa', path: '/rental-properties/idyllic-villa' },
      { name: 'Monarch Cottage', path: '/rental-properties/monarch-cottage' },
      { name: 'Palladio\u2019s View', path: '/rental-properties/palladio%E2%80%99s-view' },
      { name: 'Pebble Cove', path: '/rental-properties/pebble-cove' },
      { name: 'Sea Palms', path: '/rental-properties/sea-palms' },
      { name: 'Seagrape Estate', path: '/rental-properties/seagrape-estate' },
      { name: 'Southern Exposure', path: '/rental-properties/southern-exposure' },
      { name: 'Villa Bijou', path: '/rental-properties/villa-bijou' },
      { name: 'Villa Madeira', path: '/rental-properties/villa-madeira' },
    ],
  },
  {
    bedrooms: 4,
    label: '4 Bedrooms',
    properties: [
      { name: 'Beija Flor', path: '/rental-properties/beija-flor' },
      { name: 'Blue Agave', path: '/rental-properties/blue-agave' },
      { name: 'Cinnamon Stones', path: '/rental-properties/cinnamon-stones' },
      { name: 'Coral Sky Villa', path: '/rental-properties/coral-sky-villa' },
      { name: 'Drake\u2019s View', path: '/rental-properties/drake%E2%80%99s-view' },
      { name: 'Great Escape', path: '/rental-properties/great-escape' },
      { name: 'Halcyon Days', path: '/rental-properties/halcyon-days' },
      { name: 'Hart Bay Great House', path: '/rental-properties/hart-bay-great-house' },
      { name: 'Mad-de-Lis', path: '/rental-properties/mad-de-lis' },
      { name: 'Oceanport Villa', path: '/rental-properties/oceanport-villa' },
      { name: 'Palm Ridge', path: '/rental-properties/palm-ridge' },
      { name: 'Reef Bay Holiday Villa', path: '/rental-properties/reef-bay-holiday-villa' },
      { name: 'Sapphire Sunrise', path: '/rental-properties/sapphire-sunrise' },
      { name: 'Serenity Vista Villa', path: '/rental-properties/serenity-vista-villa' },
      { name: 'Villa Kia Orana', path: '/rental-properties/villa-kia-orana' },
      { name: 'Villa South Palm', path: '/rental-properties/villa-south-palm' },
      { name: 'Villa de Paz', path: '/rental-properties/villa-de-paz' },
    ],
  },
  {
    bedrooms: 5,
    label: '5 Bedrooms',
    properties: [
      { name: 'Argonauta', path: '/rental-properties/argonauta' },
      { name: 'Seacove Villa', path: '/rental-properties/seacove-villa' },
      { name: 'Villa Ixora', path: '/rental-properties/villa-ixora' },
    ],
  },
  {
    bedrooms: 6,
    label: '6 Bedrooms',
    properties: [
      { name: 'Casa Del Palmas', path: '/rental-properties/casa-del-palmas' },
      { name: 'Chateau Margot', path: '/rental-properties/chateau-margot' },
      { name: 'Oceana Villa', path: '/rental-properties/oceana' },
    ],
  },
]
